openshift:

  credentials:
    admin:
      username: "{{ CLUSTER_USERNAME }}"
      # Should be 14+ chars, upper and lower, with special characters
      password: "{{ CLUSTER_PASSWORD }}"
    users:
      - username: "admin"
        password: "{{ CLUSTER_PASSWORD }}"
        group: "cluster-admins"
      - username: "viewer"
        password: "{{ CLUSTER_PASSWORD }}"
        group: "cluster-admins"

  clusters:

    - name: mt-demo-1
      type: rosa # local, hcp, rosa, aro
      version: 4.17.4
      compute:
        workers: 6
      providerCredentials:
        aws_access_key_id: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_access_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "us-east-2"
        rosa_token: "{{ ROSA_TOKEN }}"
      create: true
      validate_certs: false
      workshop:
        chart:
          enabled: true
          name: gitlab-argocd-cicd
          version: 0.0.3
          repo: https://poc-examples.github.io/workshops
      gitops:
        enabled: true
        channel: gitops-1.14
        namespace: openshift-gitops
      secrets:
        vault:
          enabled: true
        namespace: secrets-manager
        # Optional: This section optional creates additional user defined secrets.
        # The Secrets are placed in the set secrets.namespace and are accessible with the k8s clustersecretstore.
        pushSecrets: []
